site_name: Web Apollo
pages:
- ['index.md', 'Index']
- ['Introduction.md', 'Introduction']
- ['Quick_start_guide.md', 'Quick-start guide']
- ['Prerequisites.md', 'Pre-requisites']
- ['Database_setup.md', 'Database setup']
- ['Configure.md', 'Configure']
- ['Data_loading.md', 'Data loading']
- ['Build.md', 'Build']
- ['Deploy.md', 'Deploy']
- ['Troubleshooting.md', 'Troubleshooting']
- ['Developer.md', 'Developers guide']

