site_name: Web Apollo 2.0
pages:
- ['index.md', 'Index']
- ['Prerequisites.md', 'Pre-requisites']
- ['Apollo2Build.md', 'Web Apollo 2.0 quick-setup']
- ['Configure.md', 'Configure']
- ['Data_loading.md', 'Data loading']
- ['Build.md', 'Build']
- ['Troubleshooting.md', 'Troubleshooting']
- ['Testing_notes.md', 'Testing notes']
- ['Architecture.md', 'Architecture']
